### PR TITLE
Add support for Kohana 3.4 (and later)

### PR DESCRIPTION
**Pull request by guss77**

### CODE REVIEW

**Comment by tommcdo** [comment]
Some preliminary feedback:

* [Squash](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) the "fixed typo" commit into the first.
* This packages uses [semantic versioning](http://semver.org/) for version numbers, which dictates that we should use `1.1.0`, as this is a backwards-compatible change with new functionality.
  - I'm not totally sure it's backwards-compatible, haven't tested.
  - You could argue that it's a patch or bug fix and not new functionality, so we'd use `1.0.2`.

I'll let @paquettg take a closer look at this before merging.

**Comment by paquettg** [comment]
I agree with tom on all points. This does not add any new functionality, the read me does not need to be updated and anyone using 1.0.* will not have any problems with this patch so it should definitly be 1.0.2, not 1.1.0 (or 1.0.1.1... which is even stranger)

on the other hand, the tests seem to fail with this adition, which is a big no no
https://travis-ci.org/tommcdo/kohana-twig/builds/60822091
squash your commits, change the version number and figure out why the test fails and i'll be a happy camper (I don't like camping though)

**Comment by paquettg** [comment]
It has been brought to my attention that the tests have been failing since pull request #9 so you can ignore that part.

**Comment by guss77** [comment]
Got it.

**Comment by guss77** [comment]
I've changed the pull request as requested, please review?

Thanks!

**Comment by guss77** [comment]
Guys, any update on this?

**Comment by tommcdo** [comment]
Sorry for the delay. Looks good.

**Pull request merged**
